[package]
name = "token"
version = "1.0.0"
authors = []

[addresses]
aptos_asset = "773aa22a10f5b3d542478a81b448a8c95815f6323eb626c965d918b23dcea3e2"
admin = "0xA"
mint_user = "0xB"
user = "0xC"
user1 = "0xD"
user2 = "0xE"
tests = "0xCAFE"  # <- THIS LINE is critical for your unit test modules

std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
aptos_token_objects = "0x4"



[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "testnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "testnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "testnet" }


